/*
Lite API

The **Lite API** can be used to to do the following  Get room rates & availability for a set of hotels Select a specific hotel with room availability and make a booking Manage the bookings - retrieve and cancel existing bookings Get static content for hotels, search hotels by destination

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
)


// SearchApiService SearchApi service
type SearchApiService service

type ApiHotelsGetRequest struct {
	ctx context.Context
	ApiService *SearchApiService
	hotelIds *string
	checkin *string
	checkout *string
	currency *string
	guestNationality *string
	adults *int32
	children *string
	guestId *string
}

// List of hotelIds
func (r ApiHotelsGetRequest) HotelIds(hotelIds string) ApiHotelsGetRequest {
	r.hotelIds = &hotelIds
	return r
}

// Check in data in YYYY-MM-DD format
func (r ApiHotelsGetRequest) Checkin(checkin string) ApiHotelsGetRequest {
	r.checkin = &checkin
	return r
}

// Check out data in YYYY-MM-DD format
func (r ApiHotelsGetRequest) Checkout(checkout string) ApiHotelsGetRequest {
	r.checkout = &checkout
	return r
}

// Currency code - example (USD)
func (r ApiHotelsGetRequest) Currency(currency string) ApiHotelsGetRequest {
	r.currency = &currency
	return r
}

// Guest nationality ISO-2 code - example (SG)
func (r ApiHotelsGetRequest) GuestNationality(guestNationality string) ApiHotelsGetRequest {
	r.guestNationality = &guestNationality
	return r
}

// Number of adult guests staying
func (r ApiHotelsGetRequest) Adults(adults int32) ApiHotelsGetRequest {
	r.adults = &adults
	return r
}

// Number of children staying if any
func (r ApiHotelsGetRequest) Children(children string) ApiHotelsGetRequest {
	r.children = &children
	return r
}

// Unique traveler ID if available
func (r ApiHotelsGetRequest) GuestId(guestId string) ApiHotelsGetRequest {
	r.guestId = &guestId
	return r
}

func (r ApiHotelsGetRequest) Execute() (map[string]interface{}, *http.Response, error) {
	return r.ApiService.HotelsGetExecute(r)
}

/*
HotelsGet hotel minimum rates availability

**Hotel Minimum Rates API** is to search and return the minimum room rates that are available for a list of hotel ID's on the specified search dates.

For each hotel ID, the minimum room rate that is available is returned.

The API also has a built in loyalty rewards system. The system rewards return users who have made prior bookings.

If the search is coming from a known guest ID, the guest level is also returned along with pricing has more discounts.

If it is a new user, the guest ID will be generated at the time of the first confirmed booking.

 Example API key for test: sand_c0155ab8-c683-4f26-8f94-b5e92c5797b9

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiHotelsGetRequest
*/
func (a *SearchApiService) HotelsGet(ctx context.Context) ApiHotelsGetRequest {
	return ApiHotelsGetRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return map[string]interface{}
func (a *SearchApiService) HotelsGetExecute(r ApiHotelsGetRequest) (map[string]interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  map[string]interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SearchApiService.HotelsGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/hotels"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.hotelIds == nil {
		return localVarReturnValue, nil, reportError("hotelIds is required and must be specified")
	}
	if r.checkin == nil {
		return localVarReturnValue, nil, reportError("checkin is required and must be specified")
	}
	if r.checkout == nil {
		return localVarReturnValue, nil, reportError("checkout is required and must be specified")
	}
	if r.currency == nil {
		return localVarReturnValue, nil, reportError("currency is required and must be specified")
	}
	if r.guestNationality == nil {
		return localVarReturnValue, nil, reportError("guestNationality is required and must be specified")
	}
	if r.adults == nil {
		return localVarReturnValue, nil, reportError("adults is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "hotelIds", r.hotelIds, "")
	parameterAddToHeaderOrQuery(localVarQueryParams, "checkin", r.checkin, "")
	parameterAddToHeaderOrQuery(localVarQueryParams, "checkout", r.checkout, "")
	parameterAddToHeaderOrQuery(localVarQueryParams, "currency", r.currency, "")
	parameterAddToHeaderOrQuery(localVarQueryParams, "guestNationality", r.guestNationality, "")
	parameterAddToHeaderOrQuery(localVarQueryParams, "adults", r.adults, "")
	if r.children != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "children", r.children, "")
	}
	if r.guestId != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "guestId", r.guestId, "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["apikeyAuth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["X-API-Key"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v map[string]interface{}
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v map[string]interface{}
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiHotelsRatesGetRequest struct {
	ctx context.Context
	ApiService *SearchApiService
	hotelIds *string
	checkin *string
	checkout *string
	guestNationality *string
	currency *string
	adults *int32
	children *string
	guestId *string
}

// List of hotelIds
func (r ApiHotelsRatesGetRequest) HotelIds(hotelIds string) ApiHotelsRatesGetRequest {
	r.hotelIds = &hotelIds
	return r
}

// Check in data in YYYY-MM-DD format
func (r ApiHotelsRatesGetRequest) Checkin(checkin string) ApiHotelsRatesGetRequest {
	r.checkin = &checkin
	return r
}

// Check out data in YYYY-MM-DD format
func (r ApiHotelsRatesGetRequest) Checkout(checkout string) ApiHotelsRatesGetRequest {
	r.checkout = &checkout
	return r
}

// Guest nationality ISO-2 code - example (SG)
func (r ApiHotelsRatesGetRequest) GuestNationality(guestNationality string) ApiHotelsRatesGetRequest {
	r.guestNationality = &guestNationality
	return r
}

// Currency code - example (USD)
func (r ApiHotelsRatesGetRequest) Currency(currency string) ApiHotelsRatesGetRequest {
	r.currency = &currency
	return r
}

// Number of adult guests staying
func (r ApiHotelsRatesGetRequest) Adults(adults int32) ApiHotelsRatesGetRequest {
	r.adults = &adults
	return r
}

// Number of children staying if any
func (r ApiHotelsRatesGetRequest) Children(children string) ApiHotelsRatesGetRequest {
	r.children = &children
	return r
}

// Unique traveler ID if available
func (r ApiHotelsRatesGetRequest) GuestId(guestId string) ApiHotelsRatesGetRequest {
	r.guestId = &guestId
	return r
}

func (r ApiHotelsRatesGetRequest) Execute() (map[string]interface{}, *http.Response, error) {
	return r.ApiService.HotelsRatesGetExecute(r)
}

/*
HotelsRatesGet hotel full rates availability

The Full Rates  API is to search and return all available rooms along with its rates, cancellation policies for a list of hotel ID's based on the search dates. 

For each hotel ID, all available room information is returned. 

The API also has a built in loyalty rewards system. The system rewards return users who have made prior bookings. 

If the search is coming from a known guest ID, the guest level is also returned along with the pricing that's appropriate for the guest level.

If it is a new user, the guest ID will be generated at the time of the first confirmed booking.

 Example API key for test: sand_c0155ab8-c683-4f26-8f94-b5e92c5797b9

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiHotelsRatesGetRequest
*/
func (a *SearchApiService) HotelsRatesGet(ctx context.Context) ApiHotelsRatesGetRequest {
	return ApiHotelsRatesGetRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return map[string]interface{}
func (a *SearchApiService) HotelsRatesGetExecute(r ApiHotelsRatesGetRequest) (map[string]interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  map[string]interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SearchApiService.HotelsRatesGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/hotels/rates"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.hotelIds == nil {
		return localVarReturnValue, nil, reportError("hotelIds is required and must be specified")
	}
	if r.checkin == nil {
		return localVarReturnValue, nil, reportError("checkin is required and must be specified")
	}
	if r.checkout == nil {
		return localVarReturnValue, nil, reportError("checkout is required and must be specified")
	}
	if r.guestNationality == nil {
		return localVarReturnValue, nil, reportError("guestNationality is required and must be specified")
	}
	if r.currency == nil {
		return localVarReturnValue, nil, reportError("currency is required and must be specified")
	}
	if r.adults == nil {
		return localVarReturnValue, nil, reportError("adults is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "hotelIds", r.hotelIds, "")
	parameterAddToHeaderOrQuery(localVarQueryParams, "checkin", r.checkin, "")
	parameterAddToHeaderOrQuery(localVarQueryParams, "checkout", r.checkout, "")
	parameterAddToHeaderOrQuery(localVarQueryParams, "guestNationality", r.guestNationality, "")
	parameterAddToHeaderOrQuery(localVarQueryParams, "currency", r.currency, "")
	parameterAddToHeaderOrQuery(localVarQueryParams, "adults", r.adults, "")
	if r.children != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "children", r.children, "")
	}
	if r.guestId != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "guestId", r.guestId, "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["apikeyAuth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["X-API-Key"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v map[string]interface{}
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
