/*
Lite API

The **Lite API** can be used to to do the following  Get room rates & availability for a set of hotels Select a specific hotel with room availability and make a booking Manage the bookings - retrieve and cancel existing bookings Get static content for hotels, search hotels by destination

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the RatesBookPostRequestPayment type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RatesBookPostRequestPayment{}

// RatesBookPostRequestPayment struct for RatesBookPostRequestPayment
type RatesBookPostRequestPayment struct {
	HolderName string `json:"holderName"`
	Number *string `json:"number,omitempty"`
	ExpireDate *string `json:"expireDate,omitempty"`
	Cvc *string `json:"cvc,omitempty"`
	Method string `json:"method"`
	Token *string `json:"token,omitempty"`
}

// NewRatesBookPostRequestPayment instantiates a new RatesBookPostRequestPayment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRatesBookPostRequestPayment(holderName string, method string) *RatesBookPostRequestPayment {
	this := RatesBookPostRequestPayment{}
	this.HolderName = holderName
	this.Method = method
	return &this
}

// NewRatesBookPostRequestPaymentWithDefaults instantiates a new RatesBookPostRequestPayment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRatesBookPostRequestPaymentWithDefaults() *RatesBookPostRequestPayment {
	this := RatesBookPostRequestPayment{}
	return &this
}

// GetHolderName returns the HolderName field value
func (o *RatesBookPostRequestPayment) GetHolderName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HolderName
}

// GetHolderNameOk returns a tuple with the HolderName field value
// and a boolean to check if the value has been set.
func (o *RatesBookPostRequestPayment) GetHolderNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HolderName, true
}

// SetHolderName sets field value
func (o *RatesBookPostRequestPayment) SetHolderName(v string) {
	o.HolderName = v
}

// GetNumber returns the Number field value if set, zero value otherwise.
func (o *RatesBookPostRequestPayment) GetNumber() string {
	if o == nil || IsNil(o.Number) {
		var ret string
		return ret
	}
	return *o.Number
}

// GetNumberOk returns a tuple with the Number field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RatesBookPostRequestPayment) GetNumberOk() (*string, bool) {
	if o == nil || IsNil(o.Number) {
		return nil, false
	}
	return o.Number, true
}

// HasNumber returns a boolean if a field has been set.
func (o *RatesBookPostRequestPayment) HasNumber() bool {
	if o != nil && !IsNil(o.Number) {
		return true
	}

	return false
}

// SetNumber gets a reference to the given string and assigns it to the Number field.
func (o *RatesBookPostRequestPayment) SetNumber(v string) {
	o.Number = &v
}

// GetExpireDate returns the ExpireDate field value if set, zero value otherwise.
func (o *RatesBookPostRequestPayment) GetExpireDate() string {
	if o == nil || IsNil(o.ExpireDate) {
		var ret string
		return ret
	}
	return *o.ExpireDate
}

// GetExpireDateOk returns a tuple with the ExpireDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RatesBookPostRequestPayment) GetExpireDateOk() (*string, bool) {
	if o == nil || IsNil(o.ExpireDate) {
		return nil, false
	}
	return o.ExpireDate, true
}

// HasExpireDate returns a boolean if a field has been set.
func (o *RatesBookPostRequestPayment) HasExpireDate() bool {
	if o != nil && !IsNil(o.ExpireDate) {
		return true
	}

	return false
}

// SetExpireDate gets a reference to the given string and assigns it to the ExpireDate field.
func (o *RatesBookPostRequestPayment) SetExpireDate(v string) {
	o.ExpireDate = &v
}

// GetCvc returns the Cvc field value if set, zero value otherwise.
func (o *RatesBookPostRequestPayment) GetCvc() string {
	if o == nil || IsNil(o.Cvc) {
		var ret string
		return ret
	}
	return *o.Cvc
}

// GetCvcOk returns a tuple with the Cvc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RatesBookPostRequestPayment) GetCvcOk() (*string, bool) {
	if o == nil || IsNil(o.Cvc) {
		return nil, false
	}
	return o.Cvc, true
}

// HasCvc returns a boolean if a field has been set.
func (o *RatesBookPostRequestPayment) HasCvc() bool {
	if o != nil && !IsNil(o.Cvc) {
		return true
	}

	return false
}

// SetCvc gets a reference to the given string and assigns it to the Cvc field.
func (o *RatesBookPostRequestPayment) SetCvc(v string) {
	o.Cvc = &v
}

// GetMethod returns the Method field value
func (o *RatesBookPostRequestPayment) GetMethod() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Method
}

// GetMethodOk returns a tuple with the Method field value
// and a boolean to check if the value has been set.
func (o *RatesBookPostRequestPayment) GetMethodOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Method, true
}

// SetMethod sets field value
func (o *RatesBookPostRequestPayment) SetMethod(v string) {
	o.Method = v
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *RatesBookPostRequestPayment) GetToken() string {
	if o == nil || IsNil(o.Token) {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RatesBookPostRequestPayment) GetTokenOk() (*string, bool) {
	if o == nil || IsNil(o.Token) {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *RatesBookPostRequestPayment) HasToken() bool {
	if o != nil && !IsNil(o.Token) {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *RatesBookPostRequestPayment) SetToken(v string) {
	o.Token = &v
}

func (o RatesBookPostRequestPayment) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RatesBookPostRequestPayment) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["holderName"] = o.HolderName
	if !IsNil(o.Number) {
		toSerialize["number"] = o.Number
	}
	if !IsNil(o.ExpireDate) {
		toSerialize["expireDate"] = o.ExpireDate
	}
	if !IsNil(o.Cvc) {
		toSerialize["cvc"] = o.Cvc
	}
	toSerialize["method"] = o.Method
	if !IsNil(o.Token) {
		toSerialize["token"] = o.Token
	}
	return toSerialize, nil
}

type NullableRatesBookPostRequestPayment struct {
	value *RatesBookPostRequestPayment
	isSet bool
}

func (v NullableRatesBookPostRequestPayment) Get() *RatesBookPostRequestPayment {
	return v.value
}

func (v *NullableRatesBookPostRequestPayment) Set(val *RatesBookPostRequestPayment) {
	v.value = val
	v.isSet = true
}

func (v NullableRatesBookPostRequestPayment) IsSet() bool {
	return v.isSet
}

func (v *NullableRatesBookPostRequestPayment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRatesBookPostRequestPayment(val *RatesBookPostRequestPayment) *NullableRatesBookPostRequestPayment {
	return &NullableRatesBookPostRequestPayment{value: val, isSet: true}
}

func (v NullableRatesBookPostRequestPayment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRatesBookPostRequestPayment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


