/*
Lite API

lite api hotel booking api

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetData200ResponseDataInner struct for GetData200ResponseDataInner
type GetData200ResponseDataInner struct {
	Id                        *int32                               `json:"id,omitempty"`
	Name                      *string                              `json:"name,omitempty"`
	HotelDescription          *string                              `json:"hotel_description,omitempty"`
	HotelImportantInformation *string                              `json:"hotel_important_information,omitempty"`
	Currency                  *string                              `json:"currency,omitempty"`
	Country                   *string                              `json:"country,omitempty"`
	City                      *string                              `json:"city,omitempty"`
	Location                  *GetData200ResponseDataInnerLocation `json:"location,omitempty"`
	Address                   *string                              `json:"address,omitempty"`
	Zip                       *string                              `json:"zip,omitempty"`
	IsClosed                  *bool                                `json:"is_closed,omitempty"`
	CreditcardRequired        *bool                                `json:"creditcard_required,omitempty"`
}

// NewGetData200ResponseDataInner instantiates a new GetData200ResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetData200ResponseDataInner() *GetData200ResponseDataInner {
	this := GetData200ResponseDataInner{}
	return &this
}

// NewGetData200ResponseDataInnerWithDefaults instantiates a new GetData200ResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetData200ResponseDataInnerWithDefaults() *GetData200ResponseDataInner {
	this := GetData200ResponseDataInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetData200ResponseDataInner) GetId() int32 {
	if o == nil || isNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetData200ResponseDataInner) GetIdOk() (*int32, bool) {
	if o == nil || isNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetData200ResponseDataInner) HasId() bool {
	if o != nil && !isNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *GetData200ResponseDataInner) SetId(v int32) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetData200ResponseDataInner) GetName() string {
	if o == nil || isNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetData200ResponseDataInner) GetNameOk() (*string, bool) {
	if o == nil || isNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GetData200ResponseDataInner) HasName() bool {
	if o != nil && !isNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetData200ResponseDataInner) SetName(v string) {
	o.Name = &v
}

// GetHotelDescription returns the HotelDescription field value if set, zero value otherwise.
func (o *GetData200ResponseDataInner) GetHotelDescription() string {
	if o == nil || isNil(o.HotelDescription) {
		var ret string
		return ret
	}
	return *o.HotelDescription
}

// GetHotelDescriptionOk returns a tuple with the HotelDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetData200ResponseDataInner) GetHotelDescriptionOk() (*string, bool) {
	if o == nil || isNil(o.HotelDescription) {
		return nil, false
	}
	return o.HotelDescription, true
}

// HasHotelDescription returns a boolean if a field has been set.
func (o *GetData200ResponseDataInner) HasHotelDescription() bool {
	if o != nil && !isNil(o.HotelDescription) {
		return true
	}

	return false
}

// SetHotelDescription gets a reference to the given string and assigns it to the HotelDescription field.
func (o *GetData200ResponseDataInner) SetHotelDescription(v string) {
	o.HotelDescription = &v
}

// GetHotelImportantInformation returns the HotelImportantInformation field value if set, zero value otherwise.
func (o *GetData200ResponseDataInner) GetHotelImportantInformation() string {
	if o == nil || isNil(o.HotelImportantInformation) {
		var ret string
		return ret
	}
	return *o.HotelImportantInformation
}

// GetHotelImportantInformationOk returns a tuple with the HotelImportantInformation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetData200ResponseDataInner) GetHotelImportantInformationOk() (*string, bool) {
	if o == nil || isNil(o.HotelImportantInformation) {
		return nil, false
	}
	return o.HotelImportantInformation, true
}

// HasHotelImportantInformation returns a boolean if a field has been set.
func (o *GetData200ResponseDataInner) HasHotelImportantInformation() bool {
	if o != nil && !isNil(o.HotelImportantInformation) {
		return true
	}

	return false
}

// SetHotelImportantInformation gets a reference to the given string and assigns it to the HotelImportantInformation field.
func (o *GetData200ResponseDataInner) SetHotelImportantInformation(v string) {
	o.HotelImportantInformation = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *GetData200ResponseDataInner) GetCurrency() string {
	if o == nil || isNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetData200ResponseDataInner) GetCurrencyOk() (*string, bool) {
	if o == nil || isNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *GetData200ResponseDataInner) HasCurrency() bool {
	if o != nil && !isNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *GetData200ResponseDataInner) SetCurrency(v string) {
	o.Currency = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *GetData200ResponseDataInner) GetCountry() string {
	if o == nil || isNil(o.Country) {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetData200ResponseDataInner) GetCountryOk() (*string, bool) {
	if o == nil || isNil(o.Country) {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *GetData200ResponseDataInner) HasCountry() bool {
	if o != nil && !isNil(o.Country) {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *GetData200ResponseDataInner) SetCountry(v string) {
	o.Country = &v
}

// GetCity returns the City field value if set, zero value otherwise.
func (o *GetData200ResponseDataInner) GetCity() string {
	if o == nil || isNil(o.City) {
		var ret string
		return ret
	}
	return *o.City
}

// GetCityOk returns a tuple with the City field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetData200ResponseDataInner) GetCityOk() (*string, bool) {
	if o == nil || isNil(o.City) {
		return nil, false
	}
	return o.City, true
}

// HasCity returns a boolean if a field has been set.
func (o *GetData200ResponseDataInner) HasCity() bool {
	if o != nil && !isNil(o.City) {
		return true
	}

	return false
}

// SetCity gets a reference to the given string and assigns it to the City field.
func (o *GetData200ResponseDataInner) SetCity(v string) {
	o.City = &v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *GetData200ResponseDataInner) GetLocation() GetData200ResponseDataInnerLocation {
	if o == nil || isNil(o.Location) {
		var ret GetData200ResponseDataInnerLocation
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetData200ResponseDataInner) GetLocationOk() (*GetData200ResponseDataInnerLocation, bool) {
	if o == nil || isNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *GetData200ResponseDataInner) HasLocation() bool {
	if o != nil && !isNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given GetData200ResponseDataInnerLocation and assigns it to the Location field.
func (o *GetData200ResponseDataInner) SetLocation(v GetData200ResponseDataInnerLocation) {
	o.Location = &v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *GetData200ResponseDataInner) GetAddress() string {
	if o == nil || isNil(o.Address) {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetData200ResponseDataInner) GetAddressOk() (*string, bool) {
	if o == nil || isNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *GetData200ResponseDataInner) HasAddress() bool {
	if o != nil && !isNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *GetData200ResponseDataInner) SetAddress(v string) {
	o.Address = &v
}

// GetZip returns the Zip field value if set, zero value otherwise.
func (o *GetData200ResponseDataInner) GetZip() string {
	if o == nil || isNil(o.Zip) {
		var ret string
		return ret
	}
	return *o.Zip
}

// GetZipOk returns a tuple with the Zip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetData200ResponseDataInner) GetZipOk() (*string, bool) {
	if o == nil || isNil(o.Zip) {
		return nil, false
	}
	return o.Zip, true
}

// HasZip returns a boolean if a field has been set.
func (o *GetData200ResponseDataInner) HasZip() bool {
	if o != nil && !isNil(o.Zip) {
		return true
	}

	return false
}

// SetZip gets a reference to the given string and assigns it to the Zip field.
func (o *GetData200ResponseDataInner) SetZip(v string) {
	o.Zip = &v
}

// GetIsClosed returns the IsClosed field value if set, zero value otherwise.
func (o *GetData200ResponseDataInner) GetIsClosed() bool {
	if o == nil || isNil(o.IsClosed) {
		var ret bool
		return ret
	}
	return *o.IsClosed
}

// GetIsClosedOk returns a tuple with the IsClosed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetData200ResponseDataInner) GetIsClosedOk() (*bool, bool) {
	if o == nil || isNil(o.IsClosed) {
		return nil, false
	}
	return o.IsClosed, true
}

// HasIsClosed returns a boolean if a field has been set.
func (o *GetData200ResponseDataInner) HasIsClosed() bool {
	if o != nil && !isNil(o.IsClosed) {
		return true
	}

	return false
}

// SetIsClosed gets a reference to the given bool and assigns it to the IsClosed field.
func (o *GetData200ResponseDataInner) SetIsClosed(v bool) {
	o.IsClosed = &v
}

// GetCreditcardRequired returns the CreditcardRequired field value if set, zero value otherwise.
func (o *GetData200ResponseDataInner) GetCreditcardRequired() bool {
	if o == nil || isNil(o.CreditcardRequired) {
		var ret bool
		return ret
	}
	return *o.CreditcardRequired
}

// GetCreditcardRequiredOk returns a tuple with the CreditcardRequired field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetData200ResponseDataInner) GetCreditcardRequiredOk() (*bool, bool) {
	if o == nil || isNil(o.CreditcardRequired) {
		return nil, false
	}
	return o.CreditcardRequired, true
}

// HasCreditcardRequired returns a boolean if a field has been set.
func (o *GetData200ResponseDataInner) HasCreditcardRequired() bool {
	if o != nil && !isNil(o.CreditcardRequired) {
		return true
	}

	return false
}

// SetCreditcardRequired gets a reference to the given bool and assigns it to the CreditcardRequired field.
func (o *GetData200ResponseDataInner) SetCreditcardRequired(v bool) {
	o.CreditcardRequired = &v
}

func (o GetData200ResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]any{}
	if !isNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !isNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !isNil(o.HotelDescription) {
		toSerialize["hotel_description"] = o.HotelDescription
	}
	if !isNil(o.HotelImportantInformation) {
		toSerialize["hotel_important_information"] = o.HotelImportantInformation
	}
	if !isNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !isNil(o.Country) {
		toSerialize["country"] = o.Country
	}
	if !isNil(o.City) {
		toSerialize["city"] = o.City
	}
	if !isNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	if !isNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	if !isNil(o.Zip) {
		toSerialize["zip"] = o.Zip
	}
	if !isNil(o.IsClosed) {
		toSerialize["is_closed"] = o.IsClosed
	}
	if !isNil(o.CreditcardRequired) {
		toSerialize["creditcard_required"] = o.CreditcardRequired
	}
	return json.Marshal(toSerialize)
}

type NullableGetData200ResponseDataInner struct {
	value *GetData200ResponseDataInner
	isSet bool
}

func (v NullableGetData200ResponseDataInner) Get() *GetData200ResponseDataInner {
	return v.value
}

func (v *NullableGetData200ResponseDataInner) Set(val *GetData200ResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetData200ResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetData200ResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetData200ResponseDataInner(val *GetData200ResponseDataInner) *NullableGetData200ResponseDataInner {
	return &NullableGetData200ResponseDataInner{value: val, isSet: true}
}

func (v NullableGetData200ResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetData200ResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
