/*
Lite API

lite api hotel booking api

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetData200ResponseDataInnerLocation struct for GetData200ResponseDataInnerLocation
type GetData200ResponseDataInnerLocation struct {
	Latitude  *float32 `json:"latitude,omitempty"`
	Longitude *float32 `json:"longitude,omitempty"`
}

// NewGetData200ResponseDataInnerLocation instantiates a new GetData200ResponseDataInnerLocation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetData200ResponseDataInnerLocation() *GetData200ResponseDataInnerLocation {
	this := GetData200ResponseDataInnerLocation{}
	return &this
}

// NewGetData200ResponseDataInnerLocationWithDefaults instantiates a new GetData200ResponseDataInnerLocation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetData200ResponseDataInnerLocationWithDefaults() *GetData200ResponseDataInnerLocation {
	this := GetData200ResponseDataInnerLocation{}
	return &this
}

// GetLatitude returns the Latitude field value if set, zero value otherwise.
func (o *GetData200ResponseDataInnerLocation) GetLatitude() float32 {
	if o == nil || isNil(o.Latitude) {
		var ret float32
		return ret
	}
	return *o.Latitude
}

// GetLatitudeOk returns a tuple with the Latitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetData200ResponseDataInnerLocation) GetLatitudeOk() (*float32, bool) {
	if o == nil || isNil(o.Latitude) {
		return nil, false
	}
	return o.Latitude, true
}

// HasLatitude returns a boolean if a field has been set.
func (o *GetData200ResponseDataInnerLocation) HasLatitude() bool {
	if o != nil && !isNil(o.Latitude) {
		return true
	}

	return false
}

// SetLatitude gets a reference to the given float32 and assigns it to the Latitude field.
func (o *GetData200ResponseDataInnerLocation) SetLatitude(v float32) {
	o.Latitude = &v
}

// GetLongitude returns the Longitude field value if set, zero value otherwise.
func (o *GetData200ResponseDataInnerLocation) GetLongitude() float32 {
	if o == nil || isNil(o.Longitude) {
		var ret float32
		return ret
	}
	return *o.Longitude
}

// GetLongitudeOk returns a tuple with the Longitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetData200ResponseDataInnerLocation) GetLongitudeOk() (*float32, bool) {
	if o == nil || isNil(o.Longitude) {
		return nil, false
	}
	return o.Longitude, true
}

// HasLongitude returns a boolean if a field has been set.
func (o *GetData200ResponseDataInnerLocation) HasLongitude() bool {
	if o != nil && !isNil(o.Longitude) {
		return true
	}

	return false
}

// SetLongitude gets a reference to the given float32 and assigns it to the Longitude field.
func (o *GetData200ResponseDataInnerLocation) SetLongitude(v float32) {
	o.Longitude = &v
}

func (o GetData200ResponseDataInnerLocation) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]any{}
	if !isNil(o.Latitude) {
		toSerialize["latitude"] = o.Latitude
	}
	if !isNil(o.Longitude) {
		toSerialize["longitude"] = o.Longitude
	}
	return json.Marshal(toSerialize)
}

type NullableGetData200ResponseDataInnerLocation struct {
	value *GetData200ResponseDataInnerLocation
	isSet bool
}

func (v NullableGetData200ResponseDataInnerLocation) Get() *GetData200ResponseDataInnerLocation {
	return v.value
}

func (v *NullableGetData200ResponseDataInnerLocation) Set(val *GetData200ResponseDataInnerLocation) {
	v.value = val
	v.isSet = true
}

func (v NullableGetData200ResponseDataInnerLocation) IsSet() bool {
	return v.isSet
}

func (v *NullableGetData200ResponseDataInnerLocation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetData200ResponseDataInnerLocation(val *GetData200ResponseDataInnerLocation) *NullableGetData200ResponseDataInnerLocation {
	return &NullableGetData200ResponseDataInnerLocation{value: val, isSet: true}
}

func (v NullableGetData200ResponseDataInnerLocation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetData200ResponseDataInnerLocation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
